
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primarYou can generate a documentation site for your project (with or without descriptions) using the CLI.

First, run dbt docs generate — this command tells dbt to compile relevant information about your dbt project and warehouse into manifest.json and catalog.json files respectively. To see documentation for all columns and not just columns described in your project, ensure that you have created the models with dbt run beforehand.

Then, run dbt docs serve to use these .json files to populate a local website.y key for this table"
        tests:
          - unique
          - not_null
